import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { useReveal } from "@/hooks/useReveal";

const faqs = [
  {
    q: "Can Rendersend read my documents?",
    a: "No. Documents are encrypted with AES-256-GCM in your browser before upload. We store ciphertext only — we have no key, no plaintext, no preview.",
  },
  {
    q: "What if I lose my recovery code?",
    a: "You lose access. There is no backdoor. This is intentional — a recoverable system would mean we hold the keys, which would defeat the purpose of zero-access encryption.",
  },
  {
    q: "Is this true end-to-end encryption?",
    a: "Yes. The key lives in the URL fragment (which never reaches a server) or is derived per-recipient from a verified email. Our servers never receive it.",
  },
  {
    q: "How does it work with Claude?",
    a: "A local MCP server runs on your machine and exposes a share_html tool. Claude calls it, your browser encrypts, and only ciphertext is uploaded. Your API keys never touch us.",
  },
  {
    q: "Can I share files other than HTML?",
    a: "Not yet. Rendersend is purpose-built for HTML artifacts — reports, dashboards, and one-page briefs generated by LLMs. Other formats are on the roadmap.",
  },
];

export const FAQ = () => {
  const ref = useReveal<HTMLDivElement>();
  return (
    <section className="border-t border-border bg-background">
      <div className="container py-24 sm:py-28">
        <div ref={ref} className="reveal mx-auto max-w-[760px]">
          <div className="mb-12 text-center">
            <p className="eyebrow mb-4">FAQ</p>
            <h2 className="text-3xl text-foreground sm:text-4xl">
              Questions, answered plainly.
            </h2>
          </div>

          <Accordion type="single" collapsible className="w-full">
            {faqs.map((item, i) => (
              <AccordionItem
                key={i}
                value={`item-${i}`}
                className="border-b border-border"
              >
                <AccordionTrigger className="py-5 text-left text-[15px] font-medium text-foreground hover:no-underline">
                  {item.q}
                </AccordionTrigger>
                <AccordionContent className="pb-5 pr-8 text-sm leading-relaxed text-muted-foreground">
                  {item.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};
